//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64 [unused]
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768
//
// }
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16
//   float3 gFresnelR0;                 // Offset:   16 Size:    12
//   float gRoughness;                  // Offset:   28 Size:     4
//   float4x4 gMatTransform;            // Offset:   32 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// gSamLinearWrap                    sampler      NA          NA      S0             s4      1 
// gDiffuseMap                       texture  float4          2d      T0             t0      1 
// cbPass                            cbuffer      NA          NA     CB0            cb1      1 
// cbMaterial                        cbuffer      NA          NA     CB1            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_1
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[1:1][41], immediateIndexed, space=0
dcl_constantbuffer CB1[2:2][2], immediateIndexed, space=0
dcl_sampler S0[4:4], mode_default, space=0
dcl_resource_texture2d (float,float,float,float) T0[0:0], space=0
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xy
dcl_output o0.xyzw
dcl_temps 13
dcl_indexableTemp x0[21], 4
sample r0.xyzw, v3.xyxx, T0[0].xyzw, S0[4]
mul r0.xyzw, r0.xyzw, CB1[2][0].xyzw
dp3 r1.x, v2.xyzx, v2.xyzx
rsq r1.x, r1.x
mul r1.xyz, r1.xxxx, v2.xyzx
mov r2.xyz, -v1.xyzx
add r2.xyz, r2.xyzx, CB0[1][24].xyzx
dp3 r1.w, r2.xyzx, r2.xyzx
sqrt r1.w, r1.w
div r2.xyz, r2.xyzx, r1.wwww
mul r3.xyz, r0.xyzx, CB0[1][27].xyzx
mov r1.w, -CB1[2][1].w
add r4.w, r1.w, l(1.000000)
mov r5.xyz, r0.xyzx
mov r5.w, CB1[2][1].x
mov r4.yz, CB1[2][1].yyzy
mov r4.w, r4.w
mov x0[0].xyz, CB0[1][30].xyzx
mov x0[2].xyz, CB0[1][31].xyzx
mov x0[4].xyz, CB0[1][32].xyzx
mov x0[6].xyz, CB0[1][33].xyzx
mov x0[8].xyz, CB0[1][34].xyzx
mov x0[10].xyz, CB0[1][35].xyzx
mov x0[12].xyz, CB0[1][36].xyzx
mov x0[14].xyz, CB0[1][37].xyzx
mov x0[16].xyz, CB0[1][38].xyzx
mov x0[18].xyz, CB0[1][39].xyzx
mov x0[20].xyz, CB0[1][40].xyzx
mov r5.xyzw, r5.xyzw
mov r4.yzw, r4.yyzw
mov r1.xyz, r1.xyzx
mov r2.xyz, r2.xyzx
mov r0.xyz, l(0,0,0,0)
mov r1.w, l(0)
mov r6.xyz, r0.xyzx
mov r2.w, r1.w
loop 
  ilt r3.w, r2.w, l(3)
  breakc_z r3.w
  mov r3.w, l(1.000000)
  imul null, r4.x, r2.w, l(6)
  mov r7.xyz, x0[r4.x + 0].xyzx
  mov r8.xyz, x0[r4.x + 2].xyzx
  mov r9.x, r5.w
  mov r9.yzw, r4.yyzw
  mov r10.xyz, r5.xyzx
  mov r11.xyz, r1.xyzx
  mov r12.xyz, r2.xyzx
  mov r8.xyz, -r8.xyzx
  dp3 r4.x, r8.xyzx, r11.xyzx
  max r4.x, r4.x, l(0.000000)
  mul r7.xyz, r4.xxxx, r7.xyzx
  mov r7.xyz, r7.xyzx
  mov r8.xyz, r8.xyzx
  mov r11.xyz, r11.xyzx
  mov r12.xyz, r12.xyzx
  mov r10.xyz, r10.xyzx
  mov r9.xyzw, r9.xyzw
  mul r4.x, r9.w, l(256.000000)
  add r12.xyz, r8.xyzx, r12.xyzx
  dp3 r6.w, r12.xyzx, r12.xyzx
  rsq r6.w, r6.w
  mul r12.xyz, r6.wwww, r12.xyzx
  add r6.w, r4.x, l(8.000000)
  dp3 r7.w, r12.xyzx, r11.xyzx
  max r7.w, r7.w, l(0.000000)
  log r7.w, r7.w
  mul r4.x, r4.x, r7.w
  exp r4.x, r4.x
  mul r4.x, r4.x, r6.w
  div r4.x, r4.x, l(8.000000)
  mov r9.xyz, r9.xyzx
  mov r12.xyz, r12.xyzx
  mov r8.xyz, r8.xyzx
  dp3 r6.w, r12.xyzx, r8.xyzx
  max r6.w, r6.w, l(0.000000)
  min r6.w, r6.w, l(1.000000)
  mov r6.w, -r6.w
  add r6.w, r6.w, l(1.000000)
  mov r8.xyz, -r9.xyzx
  add r8.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mul r7.w, r6.w, r6.w
  mul r7.w, r6.w, r7.w
  mul r7.w, r6.w, r7.w
  mul r6.w, r6.w, r7.w
  mul r8.xyz, r6.wwww, r8.xyzx
  add r8.xyz, r8.xyzx, r9.xyzx
  mov r8.xyz, r8.xyzx
  mov r8.xyz, r8.xyzx
  mul r8.xyz, r4.xxxx, r8.xyzx
  add r9.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  div r8.xyz, r8.xyzx, r9.xyzx
  add r8.xyz, r8.xyzx, r10.xyzx
  mul r7.xyz, r7.xyzx, r8.xyzx
  mov r7.xyz, r7.xyzx
  mul r7.xyz, r3.wwww, r7.xyzx
  add r6.xyz, r6.xyzx, r7.xyzx
  iadd r2.w, r2.w, l(1)
endloop 
mov r6.xyz, r6.xyzx
mov r6.xyz, r6.xyzx
add r0.xyz, r3.xyzx, r6.xyzx
mov r0.w, r0.w
mov o0.xyz, r0.xyzx
mov o0.w, r0.w
ret 
// Approximately 106 instruction slots used
